backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
site_url: https://xenodochial-hamilton-db3de6.netlify.app/

media_folder: static/img
public_folder: /img

collections:
  - name: 'daily menu'
    label: 'Daily Menu'
    folder: 'content/daily-menu'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'page'
    label: 'Page'
    folder: 'content/page'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Description', name: 'description', widget: 'string' }
      - label: 'Navigation'
        name: 'menu'
        widget: 'list'
        default: ['']
  - name: 'modal'
    label: 'Modal'
    folder: 'content/modal'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Description', name: 'description', widget: 'string' }
